/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // Background layers — semantic depth
        void: '#050407',
        abyss: '#0A0810',
        deep: '#12101A',
        'deep-surface': '#1A1726',

        // Surface layers
        surface: '#1E1B2B',
        'surface-elevated': '#252134',
        'surface-interactive': '#2D2A3E',

        // Borders
        border: '#2D2A3E',
        'border-bright': '#3D3A52',
        'border-muted': '#1E1B2B',

        // Text hierarchy
        text: '#E8E4F0',
        'text-muted': '#8B8499',
        'text-dim': '#5C576E',
        'text-inverse': '#050407',

        // Brand — purple used with intent
        primary: '#A855F7',
        'primary-dim': '#7C3AED',
        'primary-muted': 'rgba(168, 85, 247, 0.1)',
        'primary-glow': 'rgba(168, 85, 247, 0.35)',

        // Secondary accents (class colors used contextually)
        secondary: '#F43F5E',
        'secondary-dim': '#881337',
        'secondary-muted': 'rgba(244, 63, 94, 0.1)',

        // Accent gold
        gold: '#FBBF24',
        'gold-dim': '#78350F',
        'gold-muted': 'rgba(251, 191, 36, 0.1)',

        // Accent cyan
        cyan: '#60A5FA',
        'cyan-dim': '#1E3A8A',
        'cyan-muted': 'rgba(96, 165, 250, 0.1)',

        // Semantic
        danger: '#EF4444',
        'danger-dim': '#7F1D1D',
        'danger-muted': 'rgba(239, 68, 68, 0.1)',
        success: '#22C55E',
        'success-dim': '#14532D',
        'success-muted': 'rgba(34, 197, 94, 0.1)',
        warning: '#F59E0B',
        'warning-dim': '#78350F',
        'warning-muted': 'rgba(245, 158, 11, 0.1)',
        info: '#60A5FA',
        'info-dim': '#1E3A8A',
        'info-muted': 'rgba(96, 165, 250, 0.1)',

        // Rarity colors (for cards/items)
        common: '#9CA3AF',
        uncommon: '#4ADE80',
        rare: '#60A5FA',
        epic: '#C084FC',
        legendary: '#FBBF24',
        mythic: '#F43F5E',
      },
      fontFamily: {
        display: ['Cinzel', 'serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-xl': ['clamp(3.5rem, 8vw, 7rem)', { lineHeight: '1.1', letterSpacing: '0.02em', fontWeight: '800' }],
        'display-lg': ['clamp(2.5rem, 5vw, 4.5rem)', { lineHeight: '1.15', letterSpacing: '0.015em', fontWeight: '800' }],
        'display-md': ['clamp(1.75rem, 3.5vw, 3rem)', { lineHeight: '1.2', letterSpacing: '0.01em', fontWeight: '700' }],
        'display-sm': ['clamp(1.25rem, 2.5vw, 2rem)', { lineHeight: '1.25', letterSpacing: '0.005em', fontWeight: '700' }],
        'heading-lg': ['1.5rem', { lineHeight: '1.3', letterSpacing: '0.005em', fontWeight: '600' }],
        'heading-md': ['1.25rem', { lineHeight: '1.35', letterSpacing: '0', fontWeight: '600' }],
        'heading-sm': ['1.125rem', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '600' }],
        'body-lg': ['1.125rem', { lineHeight: '1.7', letterSpacing: '0', fontWeight: '400' }],
        'body-md': ['1rem', { lineHeight: '1.65', letterSpacing: '0', fontWeight: '400' }],
        'body-sm': ['0.875rem', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'label-lg': ['0.875rem', { lineHeight: '1.5', letterSpacing: '0.05em', fontWeight: '600', textTransform: 'uppercase' }],
        'label-md': ['0.75rem', { lineHeight: '1.5', letterSpacing: '0.08em', fontWeight: '600', textTransform: 'uppercase' }],
        'label-sm': ['0.6875rem', { lineHeight: '1.5', letterSpacing: '0.1em', fontWeight: '600', textTransform: 'uppercase' }],
        'mono-xl': ['2.5rem', { lineHeight: '1.1', fontWeight: '700', fontFamily: 'JetBrains Mono' }],
        'mono-lg': ['1.75rem', { lineHeight: '1.15', fontWeight: '700', fontFamily: 'JetBrains Mono' }],
        'mono-md': ['1.25rem', { lineHeight: '1.2', fontWeight: '700', fontFamily: 'JetBrains Mono' }],
        'mono-sm': ['0.875rem', { lineHeight: '1.3', fontWeight: '600', fontFamily: 'JetBrains Mono' }],
        'mono-xs': ['0.75rem', { lineHeight: '1.4', fontWeight: '600', fontFamily: 'JetBrains Mono' }],
      },
      spacing: {
        'space-0': '0',
        'space-1': '0.25rem',
        'space-2': '0.5rem',
        'space-3': '0.75rem',
        'space-4': '1rem',
        'space-5': '1.25rem',
        'space-6': '1.5rem',
        'space-8': '2rem',
        'space-10': '2.5rem',
        'space-12': '3rem',
        'space-16': '4rem',
        'space-20': '5rem',
        'space-24': '6rem',
        'space-32': '8rem',
      },
      borderRadius: {
        'radius-sm': '4px',
        'radius-md': '8px',
        'radius-lg': '12px',
        'radius-xl': '16px',
        'radius-2xl': '24px',
        'radius-full': '9999px',
      },
      boxShadow: {
        'depth-1': '0 1px 3px rgba(0, 0, 0, 0.4), 0 1px 2px rgba(0, 0, 0, 0.3)',
        'depth-2': '0 4px 12px rgba(0, 0, 0, 0.45), 0 2px 4px rgba(0, 0, 0, 0.3)',
        'depth-3': '0 8px 24px rgba(0, 0, 0, 0.5), 0 4px 8px rgba(0, 0, 0, 0.35)',
        'depth-4': '0 16px 48px rgba(0, 0, 0, 0.55), 0 8px 16px rgba(0, 0, 0, 0.4)',
        'glow-primary': '0 0 24px rgba(168, 85, 247, 0.25), 0 0 48px rgba(168, 85, 247, 0.1)',
        'glow-primary-strong': '0 0 32px rgba(168, 85, 247, 0.35), 0 0 64px rgba(168, 85, 247, 0.15)',
        'glow-gold': '0 0 24px rgba(251, 191, 36, 0.25), 0 0 48px rgba(251, 191, 36, 0.1)',
        'inner-glow': 'inset 0 0 24px rgba(168, 85, 247, 0.08)',
        'card': '0 4px 24px rgba(0, 0, 0, 0.5)',
        'elevated': '0 8px 32px rgba(0, 0, 0, 0.6)',
      },
      animation: {
        'fade-in': 'fadeIn 0.4s ease-out',
        'fade-in-up': 'fadeInUp 0.5s ease-out',
        'fade-in-down': 'fadeInDown 0.5s ease-out',
        'slide-in-right': 'slideInRight 0.35s ease-out',
        'slide-in-left': 'slideInLeft 0.35s ease-out',
        'slide-in-up': 'slideInUp 0.35s ease-out',
        'slide-in-down': 'slideInDown 0.35s ease-out',
        'scale-in': 'scaleIn 0.25s ease-out',
        'scale-out': 'scaleOut 0.2s ease-in',
        'glow-pulse': 'glowPulse 2.5s ease-in-out infinite',
        'shimmer': 'shimmer 2.5s linear infinite',
        'float': 'float 4s ease-in-out infinite',
        'float-slow': 'float 6s ease-in-out infinite',
        'spin-slow': 'spin 8s linear infinite',
        'shake': 'shake 0.4s ease-in-out',
        'reveal': 'reveal 0.7s cubic-bezier(0.16, 1, 0.3, 1)',
        'reveal-up': 'revealUp 0.6s cubic-bezier(0.16, 1, 0.3, 1)',
        'reveal-down': 'revealDown 0.6s cubic-bezier(0.16, 1, 0.3, 1)',
        'bar-fill': 'barFill 1s cubic-bezier(0.16, 1, 0.3, 1)',
        'damage': 'damage 0.35s ease-out',
        'coin-spin': 'coinSpin 0.7s ease-out',
        'ripple': 'ripple 0.4s ease-out',
        'bounce-subtle': 'bounceSubtle 0.5s ease-out',
        'orbit-slow': 'orbit 30s linear infinite',
        'orbit-reverse': 'orbit 25s linear infinite reverse',
        'twinkle': 'twinkle 2s ease-in-out infinite',
        'pulse-soft': 'pulseSoft 3.5s ease-in-out infinite',
        'page-transition-enter': 'pageEnter 0.28s ease-out forwards',
        'page-transition-exit': 'pageExit 0.18s ease-in forwards',
      },
      keyframes: {
        fadeIn: { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        fadeInUp: { '0%': { opacity: '0', transform: 'translateY(16px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        fadeInDown: { '0%': { opacity: '0', transform: 'translateY(-16px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        slideInRight: { '0%': { opacity: '0', transform: 'translateX(24px)' }, '100%': { opacity: '1', transform: 'translateX(0)' } },
        slideInLeft: { '0%': { opacity: '0', transform: 'translateX(-24px)' }, '100%': { opacity: '1', transform: 'translateX(0)' } },
        slideInUp: { '0%': { opacity: '0', transform: 'translateY(24px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        slideInDown: { '0%': { opacity: '0', transform: 'translateY(-24px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        scaleIn: { '0%': { opacity: '0', transform: 'scale(0.92)' }, '100%': { opacity: '1', transform: 'scale(1)' } },
        scaleOut: { '0%': { opacity: '1', transform: 'scale(1)' }, '100%': { opacity: '0', transform: 'scale(0.92)' } },
        glowPulse: { '0%, 100%': { boxShadow: '0 0 16px rgba(168, 85, 247, 0.2)' }, '50%': { boxShadow: '0 0 32px rgba(168, 85, 247, 0.4)' } },
        shimmer: { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
        float: { '0%, 100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-12px)' } },
        shake: { '0%, 100%': { transform: 'translateX(0)' }, '25%': { transform: 'translateX(-6px)' }, '75%': { transform: 'translateX(6px)' } },
        reveal: { '0%': { opacity: '0', transform: 'scale(0.85) rotateY(60deg)' }, '100%': { opacity: '1', transform: 'scale(1) rotateY(0)' } },
        revealUp: { '0%': { opacity: '0', transform: 'translateY(24px) scale(0.95)' }, '100%': { opacity: '1', transform: 'translateY(0) scale(1)' } },
        revealDown: { '0%': { opacity: '0', transform: 'translateY(-24px) scale(0.95)' }, '100%': { opacity: '1', transform: 'translateY(0) scale(1)' } },
        barFill: { '0%': { width: '0%' }, '100%': { width: 'var(--bar-width)' } },
        damage: { '0%': { opacity: '1', transform: 'translateY(0) scale(1.3)' }, '100%': { opacity: '0', transform: 'translateY(-48px) scale(1)' } },
        coinSpin: { '0%': { transform: 'rotateY(0)' }, '100%': { transform: 'rotateY(720deg)' } },
        ripple: { '0%': { transform: 'scale(0)', opacity: '0.5' }, '100%': { transform: 'scale(2.5)', opacity: '0' } },
        bounceSubtle: { '0%, 100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-6px)' } },
        orbit: { '0%': { transform: 'rotate(0deg)' }, '100%': { transform: 'rotate(360deg)' } },
        twinkle: { '0%, 100%': { opacity: '0.2' }, '50%': { opacity: '0.8' } },
        pulseSoft: { '0%, 100%': { opacity: '0.25' }, '50%': { opacity: '0.45' } },
        pageEnter: { '0%': { opacity: '0', transform: 'translateY(6px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        pageExit: { '0%': { opacity: '1', transform: 'translateY(0)' }, '100%': { opacity: '0', transform: 'translateY(6px)' } },
      },
      backgroundImage: {
        'noise': "url(\"data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='0.03'/%3E%3C/svg%3E\")",
        'grain': "url(\"data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.65' numOctaves='3' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='0.04'/%3E%3C/svg%3E\")",
        'vignette': 'radial-gradient(ellipse at center, transparent 40%, var(--void) 100%)',
      },
      transitionDuration: {
        'fast': '120ms',
        'normal': '200ms',
        'slow': '300ms',
        'slower': '400ms',
      },
      transitionTimingFunction: {
        'ease-out-expo': 'cubic-bezier(0.16, 1, 0.3, 1)',
        'ease-in-expo': 'cubic-bezier(0.87, 0, 0.13, 1)',
        'spring': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
    },
  },
  plugins: [],
};